---
language: python
python: "3.8"

# Use the new container infrastructure
sudo: false

env:
  global:
    - ROLE_NAME: postgresql-db
  matrix:
    - POSTGRESQL_VERSION=10
    - POSTGRESQL_VERSION=11
    - POSTGRESQL_VERSION=12
# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  - mv "$PWD" "${PWD%/*}/$ROLE_NAME"
  # Install ansible
  - pip install ansible molecule docker testinfra pytest pytest-xdist

  # Check ansible version
  - ansible --version

  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
