---
- name: Converge
  hosts: all
  remote_user: ansible
  tasks:
    - name: "Include postgresql-db"
      include_role:
        name: "postgresql-db"
  vars:
    ansible_python_interpreter: auto
    postgresql_major_version: "{{ lookup('env', 'POSTGRESQL_VERSION') | default(postgresql_major_version, true) }}"
