---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
platforms:
  - name: debian10
    image: geerlingguy/docker-debian10-ansible
    tmpfs:
      - /run
      - /tmp
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    pre_build_image: true
    privileged: true
  - name: debian9
    image: geerlingguy/docker-debian9-ansible
    tmpfs:
      - /run
      - /tmp
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    pre_build_image: true
    privileged: true
  - name: debian8
    image: nekeal/debian8-ansible-systemd
    # image: percygrunwald/docker-debian8-ansible
    tmpfs:
      - /run
      - /tmp
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    pre_build_image: true
    pull: true
    privileged: true
  - name: ubuntu1804
    image: geerlingguy/docker-ubuntu1804-ansible
    tmpfs:
      - /run
      - /tmp
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    pre_build_image: true
    privileged: true
  - name: ubuntu2004
    image: geerlingguy/docker-ubuntu2004-ansible
    tmpfs:
      - /run
      - /tmp
      - /var/log/journald
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    pre_build_image: true
    privileged: true
provisioner:
  name: ansible
  log: true
  env:
    POSTGRESQL_VERSION: ${POSTGRESQL_VERSION:-""}
verifier:
  name: testinfra
  options:
    capture: no
    n: 2
